"""
encryption.py — Column-level symmetric encryption for sensitive secrets.

Used to encrypt ``User.mfa_secret`` at rest.  The encryption key is sourced
from the ``MFA_ENCRYPTION_KEY`` environment variable; if not set, it is
deterministically derived from ``SECRET_KEY`` so dev environments work
out-of-the-box without separate configuration.

In production, ``MFA_ENCRYPTION_KEY`` MUST be set to a value generated by:

    python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

and managed by a KMS / secrets manager.  Per the data-handling policy §4.2,
the JWT signing key and the MFA encryption key MUST be separate so that
compromise of one does not yield the other.

Migration path (already accommodated):
  - Old plaintext values: ``decrypt_secret()`` falls back to returning the
    raw string if Fernet decryption fails.  This is purely a transitional
    affordance — production deployment should backfill encrypted ciphertext.
"""
from __future__ import annotations

import base64
import hashlib
import os
from functools import lru_cache

from cryptography.fernet import Fernet, InvalidToken
from sqlalchemy import String, TypeDecorator
from sqlalchemy.engine.interfaces import Dialect


@lru_cache(maxsize=1)
def _get_fernet() -> Fernet:
    """
    Return the cached Fernet instance for the process.

    Resolution order:
      1. ``MFA_ENCRYPTION_KEY`` env var (must be a 32-byte url-safe-base64 key)
      2. Derived from ``SECRET_KEY`` via SHA-256 (dev fallback only)
    """
    env_key = os.getenv("MFA_ENCRYPTION_KEY")
    if env_key:
        return Fernet(env_key.encode())

    # Dev fallback: derive a Fernet key from SECRET_KEY.  Not production-safe
    # (the same key is used for JWT signing, so compromise of one yields the
    # other), but lets dev environments boot without extra config.
    secret_key = os.getenv("SECRET_KEY") or "change-me-in-production"
    digest = hashlib.sha256(secret_key.encode()).digest()
    derived = base64.urlsafe_b64encode(digest)
    return Fernet(derived)


def encrypt_secret(plaintext: str) -> str:
    """Encrypt a string with the configured Fernet key; return ciphertext (str)."""
    if plaintext is None:
        return None
    return _get_fernet().encrypt(plaintext.encode()).decode()


def decrypt_secret(ciphertext: str) -> str:
    """
    Decrypt a Fernet ciphertext.

    If the input doesn't decrypt cleanly (legacy plaintext from before
    encryption was introduced), return it unchanged.  This is a transitional
    affordance — once production data is fully encrypted, the fallback can
    be removed and the function can raise InvalidToken instead.
    """
    if ciphertext is None:
        return None
    try:
        return _get_fernet().decrypt(ciphertext.encode()).decode()
    except (InvalidToken, ValueError):
        # Legacy plaintext row from before encryption was introduced
        return ciphertext


class EncryptedString(TypeDecorator):
    """
    SQLAlchemy column type that transparently encrypts strings at write
    and decrypts at read.  The underlying DB column is a ``String``.

    Usage:
        secret = Column(EncryptedString(256), nullable=True)

    The application code reads/writes plain strings as normal.  Length must
    be sized for ciphertext: Fernet ciphertext is roughly
    ``ceil((plaintext_len + 50) / 3) * 4`` bytes (base64).  A 32-char
    plaintext secret becomes ~120 chars of ciphertext.
    """

    impl = String
    cache_ok = True

    def process_bind_param(self, value, dialect: Dialect):
        if value is None:
            return None
        return encrypt_secret(str(value))

    def process_result_value(self, value, dialect: Dialect):
        if value is None:
            return None
        return decrypt_secret(value)
