"""add practice address columns for clustering

Revision ID: 5632b84a39f0
Revises: 925cf1b3571e
Create Date: 2026-06-14 14:48:29.033539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5632b84a39f0'
down_revision: Union[str, None] = '925cf1b3571e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('street_address', sa.String(length=200), nullable=True))
    op.add_column('providers', sa.Column('practice_zip', sa.String(length=10), nullable=True))
    op.add_column('providers', sa.Column('address_normalized', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_providers_address_normalized'), 'providers', ['address_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_address_normalized'), table_name='providers')
    op.drop_column('providers', 'address_normalized')
    op.drop_column('providers', 'practice_zip')
    op.drop_column('providers', 'street_address')
    # ### end Alembic commands ###
