"""add agent_runs table

Revision ID: 925cf1b3571e
Revises: e0b6e5d0fa74
Create Date: 2026-05-11 00:19:14.831630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '925cf1b3571e'
down_revision: Union[str, None] = 'e0b6e5d0fa74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('n_findings', sa.Integer(), nullable=True),
    sa.Column('max_severity', sa.String(length=10), nullable=True),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_target', 'agent_runs', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_target_id'), 'agent_runs', ['target_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_workflow'), 'agent_runs', ['workflow'], unique=False)
    op.create_index('ix_agent_runs_workflow_started', 'agent_runs', ['workflow', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_runs_workflow_started', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_workflow'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_target_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_target', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
